version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpassword

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  cerbos:
    image: cerbos/cerbos:latest
    ports:
      - "3592:3592"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
