apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-app-laravel-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /path/to/host/storage
